// ---------------------------------------------------------------------------
// freepieces SDK — FreePiecesClient
// ---------------------------------------------------------------------------

import type { FreePiecesClientOptions, PieceSummary, ActionResult, TriggerResult } from './types.js';
import { FreePiecesError } from './types.js';
import type { KnownPieces } from './generated/index.js';
import { knownPieceNames } from './generated/index.js';

// ---------------------------------------------------------------------------
// Helper: build a piece proxy
// ---------------------------------------------------------------------------

/**
 * Returns an object whose every method call dispatches to
 * `POST /run/<pieceName>/<actionName>` via the provided runner.
 *
 * The cast to `T` is intentional — real type safety comes from the piece
 * interfaces declared in generated/index.ts; at runtime this is an ES Proxy.
 */
function makePieceProxy<T>(
  pieceName: string,
  runner: (piece: string, action: string, props: Record<string, unknown>) => Promise<unknown>,
): T {
  return new Proxy(
    {},
    {
      get(_target, actionName: string) {
        return (props: Record<string, unknown> = {}) =>
          runner(pieceName, actionName, props);
      },
    },
  ) as T;
}

// ---------------------------------------------------------------------------
// FreePiecesClient
// ---------------------------------------------------------------------------

/**
 * Main freepieces SDK client.
 *
 * Provides:
 * - Fully-typed accessors for every installed piece (`client.gmail`, `client.slack`, …)
 * - A generic escape-hatch `client.run(piece, action, props)` for custom or AP pieces
 * - `client.listPieces()` to enumerate all registered pieces at runtime
 *
 * Typed piece properties (e.g. `client.gmail`) are added via declaration
 * merging with `KnownPieces` (auto-generated in `generated/index.ts`) and
 * populated at runtime by iterating over `knownPieceNames`.
 *
 * @example
 * ```ts
 * import { createClient } from 'freepieces/sdk';
 *
 * // Production — token is the shared FREEPIECES_RUN_API_KEY secret, userId identifies
 * // the user whose stored OAuth2 token should be retrieved from KV.
 * const client = createClient({
 *   baseUrl: 'https://freepieces.example.workers.dev',
 *   token:   process.env.FREEPIECES_RUN_API_KEY,   // fp_sk_<hex32>
 *   userId:  'alice@example.com',
 * });
 *
 * // Typed Gmail call
 * await client.gmail.send_email({
 *   receiver: ['someone@example.com'],
 *   subject:  'Hello from SDK',
 *   body:     'It works!',
 * });
 *
 * // Generic escape-hatch
 * await client.run('my-custom-piece', 'my-action', { foo: 'bar' });
 * ```
 */
// Declaration merging: adds every KnownPieces key as a typed property on FreePiecesClient.
// The properties are set at runtime in the constructor via the knownPieceNames loop.
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface FreePiecesClient extends KnownPieces {}
export class FreePiecesClient {
  private readonly baseUrl: string;
  private readonly token: string | undefined;
  private readonly accessToken: string | undefined;
  private readonly userId: string | undefined;
  private readonly pieceToken: string | undefined;
  private readonly fetchFn: typeof globalThis.fetch;

  constructor(options: FreePiecesClientOptions) {
    const url = options.baseUrl.replace(/\/$/, '');
    this.baseUrl  = url;
    this.token    = options.token;
    this.accessToken = options.accessToken;
    this.userId   = options.userId;
    this.pieceToken = options.pieceToken;
    this.fetchFn  = options.fetch ?? globalThis.fetch.bind(globalThis);

    // Populate a typed proxy for every registered piece.
    // KnownPieces + knownPieceNames are regenerated by `fp install`.
    for (const name of knownPieceNames) {
      (this as Record<string, unknown>)[name] = makePieceProxy(name, this.run.bind(this));
    }
  }

  // ── Core HTTP helpers ────────────────────────────────────────────────────

  private headers(): Record<string, string> {
    const h: Record<string, string> = { 'content-type': 'application/json' };

    // Bearer precedence: OpenAuth JWT > static API key > pieceToken > userId
    const bearer = this.accessToken ?? this.token ?? this.pieceToken ?? this.userId;
    if (bearer) h['authorization'] = `Bearer ${bearer}`;
    if (this.userId) h['x-user-id'] = this.userId;
    if (this.pieceToken) h['x-piece-token'] = this.pieceToken;

    return h;
  }

  private async request<T>(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<T> {
    const response = await this.fetchFn(`${this.baseUrl}${path}`, {
      method,
      headers: this.headers(),
      ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
    });

    const data: unknown = await response.json();

    if (!response.ok) {
      throw new FreePiecesError(
        response.status,
        data,
        `freepieces request failed (${response.status} ${method} ${path}): ${JSON.stringify(data)}`,
      );
    }

    return data as T;
  }

  // ── Public API ───────────────────────────────────────────────────────────

  /**
   * Call any piece action — useful for custom-installed or AP pieces where
   * a static typed accessor is not available.
   *
   * @param piece  - Piece name as registered on the worker (e.g. `'gmail'`)
   * @param action - Action name (e.g. `'send_email'`)
   * @param props  - Props to pass to the action
   */
  async run<T = unknown>(
    piece: string,
    action: string,
    props: Record<string, unknown> = {},
  ): Promise<ActionResult<T>> {
    return this.request<T>('POST', `/run/${piece}/${action}`, props);
  }

  /**
   * Fetch the list of all pieces registered on the worker, including their
   * actions and auth type.
   */
  async listPieces(): Promise<PieceSummary[]> {
    return this.request<PieceSummary[]>('GET', '/pieces');
  }

  /**
   * Invoke a trigger directly (synchronous). Useful for polling triggers and
   * for testing webhook/queue trigger filters.
   *
   * @param piece       - Piece name (e.g. `'gmail'`)
   * @param trigger     - Trigger name (e.g. `'gmail_new_email_received'`)
   * @param body        - Trigger body: `{ propsValue?, lastPollMs?, payload? }`
   */
  async trigger<T = unknown>(
    piece: string,
    trigger: string,
    body: { propsValue?: Record<string, unknown>; lastPollMs?: number; payload?: unknown } = {},
  ): Promise<TriggerResult<T>> {
    return this.request<TriggerResult<T>>('POST', `/trigger/${piece}/${trigger}`, body);
  }

  /**
   * Access a piece by its runtime-string name and get a dynamic proxy.
   * Useful when the piece name is only known at runtime.
   *
   * @example
   * ```ts
   * const myPiece = client.piece<{ greet(i: { name: string }): Promise<string> }>('my-piece');
   * await myPiece.greet({ name: 'World' });
   * ```
   */
  piece<T = Record<string, (props?: Record<string, unknown>) => Promise<unknown>>>(
    name: string,
  ): T {
    return makePieceProxy<T>(name, this.run.bind(this));
  }
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Create a new freepieces SDK client.
 *
 * @example
 * ```ts
 * import { createClient } from 'freepieces/sdk';
 *
 * const client = createClient({
 *   baseUrl: process.env.FREEPIECES_URL!,
 *   token:   process.env.FREEPIECES_RUN_API_KEY,
 *   userId:  process.env.USER_ID,
 *   pieceToken: process.env.FREEPIECES_PIECE_TOKEN,
 * });
 * ```
 */
export function createClient(options: FreePiecesClientOptions): FreePiecesClient {
  return new FreePiecesClient(options);
}
