/**
 * typegen — auto-generate type files from AP piece runtime prop structures.
 *
 * Called by `fp install` after npm-installing a piece.  Loads the piece
 * dynamically, walks every action's `props` map, and writes a type file
 * into `src/sdk/generated/`  (e.g. `src/sdk/generated/npm-slack.ts`).
 *
 * After writing per-piece types, `generateGeneratedIndex()` scans the
 * directory and writes `src/sdk/generated/index.ts` — the single barrel
 * that re-exports all piece types, the `KnownPieces` interface, and the
 * `knownPieceNames` const used by the SDK client at runtime.
 */

import { writeFile, readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { debug } from './debug.js';

// ---------------------------------------------------------------------------
// Shared file header stamped on every auto-generated file
// ---------------------------------------------------------------------------

export const AUTOGEN_HEADER =
  '/**\n' +
  ' * ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY\n' +
  ' *\n' +
  ' * Generated by `fp install`. Re-run the command to update.\n' +
  ' */\n';

// ---------------------------------------------------------------------------
// AP PropertyType → TypeScript type string
// ---------------------------------------------------------------------------

const TYPE_MAP: Record<string, string> = {
  SHORT_TEXT:       'string',
  LONG_TEXT:        'string',
  NUMBER:           'number',
  CHECKBOX:         'boolean',
  DATE_TIME:        'string',
  FILE:             'string',
  JSON:             'unknown',
  OBJECT:           'Record<string, unknown>',
  MARKDOWN:         'string',
  DROPDOWN:         'string',
  STATIC_DROPDOWN:  'string',
  MULTI_SELECT_DROPDOWN: 'string[]',
  STATIC_MULTI_SELECT_DROPDOWN: 'string[]',
  DYNAMIC:          'Record<string, unknown>',
  ARRAY:            'unknown[]',   // overridden below when sub-props exist
  CUSTOM_AUTH:      'Record<string, string>',
  SECRET_TEXT:      'string',
  OAUTH2:          'string',
  BASIC_AUTH:       'Record<string, string>',
};

function tsType(prop: PropShape): string {
  if (prop.type === 'ARRAY' && prop.properties) {
    const inner = objectLiteral(prop.properties, '  ');
    return `Array<${inner}>`;
  }
  if (prop.type === 'OBJECT' && prop.properties) {
    return objectLiteral(prop.properties, '  ');
  }
  return TYPE_MAP[prop.type] ?? 'unknown';
}

/** Render a TS object literal type from sub-props. */
function objectLiteral(
  props: Record<string, PropShape>,
  indent: string,
): string {
  const lines = Object.entries(props).map(([name, p]) => {
    const opt = p.required ? '' : '?';
    return `${indent}  ${safeName(name)}${opt}: ${tsType(p)};`;
  });
  return `{\n${lines.join('\n')}\n${indent}}`;
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

/** Pascalise a kebab/snake name: send_channel_message → SendChannelMessage */
function pascal(name: string): string {
  return name
    .replace(/[-_]([a-z])/g, (_, c: string) => c.toUpperCase())
    .replace(/^[a-z]/, (c) => c.toUpperCase());
}

function safeName(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name}'`;
}

// ---------------------------------------------------------------------------
// Minimal shapes from AP runtime objects
// ---------------------------------------------------------------------------

interface PropShape {
  type: string;
  required?: boolean;
  displayName?: string;
  description?: string;
  properties?: Record<string, PropShape>;
}

interface ApActionShape {
  name: string;
  displayName?: string;
  description?: string;
  props?: Record<string, PropShape>;
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

function emitAction(
  piecePascal: string,
  action: ApActionShape,
): { inputIface: string; clientLine: string } {
  const actionPascal = pascal(action.name);
  const inputName = `${piecePascal}${actionPascal}Input`;
  const methodName = safeName(action.name);

  const propEntries = Object.entries(action.props ?? {}).filter(
    // MARKDOWN props are display-only, never sent as input
    ([, p]) => p.type !== 'MARKDOWN',
  );

  const propLines = propEntries.map(([name, prop]) => {
    const opt = prop.required ? '' : '?';
    const desc = prop.description
      ? `  /** ${prop.description.replace(/\*\//g, '* /')} */\n`
      : '';
    return `${desc}  ${safeName(name)}${opt}: ${tsType(prop)};`;
  });

  const inputIface =
    `export interface ${inputName} {\n` +
    (propLines.length ? propLines.join('\n') + '\n' : '') +
    `}`;

  const desc = action.description ? `  /** ${action.description.replace(/\*\//g, '* /')} */\n` : '';
  const isOptional = propEntries.every(([, p]) => !p.required);
  const inputArg = isOptional ? `input?: ${inputName}` : `input: ${inputName}`;
  const clientLine = `${desc}  ${methodName}(${inputArg}): Promise<unknown>;`;

  return { inputIface, clientLine };
}

/**
 * Generate a `.d.ts` string for an AP piece loaded at runtime.
 *
 * @param pieceName - Piece name as kebab-case, e.g. `'slack'`
 * @param apPiece   - The runtime AP piece object (from `pkg.slack`)
 */
export function generatePieceTypes(
  pieceName: string,
  apPiece: {
    _actions?: Record<string, ApActionShape>;
    displayName?: string;
    description?: string;
  },
): string {
  const piecePascal = pascal(pieceName);
  const clientName = `${piecePascal}Client`;
  const actions = Object.values(apPiece._actions ?? {});

  const parts: string[] = [
    AUTOGEN_HEADER,
    `// Piece: ${apPiece.displayName ?? pieceName}`,
    '',
  ];

  const clientLines: string[] = [];

  for (const action of actions) {
    const { inputIface, clientLine } = emitAction(piecePascal, action);
    parts.push(inputIface);
    parts.push('');
    clientLines.push(clientLine);
  }

  // Client interface
  parts.push(`export interface ${clientName} {`);
  parts.push(clientLines.join('\n'));
  parts.push('}');
  parts.push('');

  return parts.join('\n');
}

/**
 * Write a `.d.ts` file next to the wrapper stub.
 *
 * @param outPath   - Full path, e.g. `src/pieces/npm-slack.d.ts`
 * @param pieceName - e.g. `'slack'`
 * @param apPiece   - The runtime AP piece object
 */
export async function writePieceTypes(
  outPath: string,
  pieceName: string,
  apPiece: Record<string, unknown>,
): Promise<void> {
  const dts = generatePieceTypes(
    pieceName,
    apPiece as Parameters<typeof generatePieceTypes>[1],
  );
  await writeFile(outPath, dts, 'utf-8');
  debug('typegen', `wrote ${outPath} (${dts.split('\n').length} lines)`);
}

// ---------------------------------------------------------------------------
// Regenerate all npm-*.ts piece type files
// ---------------------------------------------------------------------------

/** Camelise kebab: `my-piece` → `myPiece` */
function toCamel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

export interface RegenerateResult {
  pieceName: string;
  ok: boolean;
  error?: string;
}

/**
 * Scan `src/sdk/generated/` for `npm-*.ts` files and regenerate each by
 * loading the corresponding `@activepieces/piece-<name>` package at runtime.
 *
 * @param generatedDir  - Absolute path to `src/sdk/generated/`
 * @param cwd           - Project root (where node_modules lives)
 */
export async function regenerateAllPieceTypes(
  generatedDir: string,
  cwd: string,
): Promise<RegenerateResult[]> {
  const entries = await readdir(generatedDir);
  const npmFiles = entries.filter(f => f.startsWith('npm-') && f.endsWith('.ts') && f !== 'npm-gmail.ts');
  // npm-gmail.ts is auto-generated from @activepieces/piece-gmail — include it too
  const allNpmFiles = entries.filter(f => f.startsWith('npm-') && f.endsWith('.ts'));

  const results: RegenerateResult[] = [];

  for (const file of allNpmFiles) {
    const pieceName = file.replace(/^npm-/, '').replace(/\.ts$/, '');
    const pkg = `@activepieces/piece-${pieceName}`;
    const outPath = join(generatedDir, file);

    const pkgDir = join(cwd, 'node_modules', pkg);
    if (!existsSync(pkgDir)) {
      results.push({ pieceName, ok: false, error: `${pkg} not found in node_modules` });
      continue;
    }

    try {
      const exportKey = toCamel(pieceName);
      // Resolve the actual entry-point file via CJS require so ESM gets a file
      // URL (not a directory URL, which breaks with tsx and some package configs)
      const req = createRequire(join(cwd, 'package.json'));
      const entryPath = req.resolve(pkg);
      const mod = await import(pathToFileURL(entryPath).href);
      const apPiece = mod.default?.[exportKey] ?? mod[exportKey] ?? mod.default;

      if (!apPiece?._actions) {
        results.push({ pieceName, ok: false, error: `could not resolve piece object from ${pkg}` });
        continue;
      }

      await writePieceTypes(outPath, pieceName, apPiece as Record<string, unknown>);
      results.push({ pieceName, ok: true });
    } catch (err) {
      results.push({ pieceName, ok: false, error: err instanceof Error ? err.message : String(err) });
    }
  }

  return results;
}

// ---------------------------------------------------------------------------
// Generated index — KnownPieces + barrel re-exports
// ---------------------------------------------------------------------------

/**
 * Scan `src/sdk/generated/*.ts` and write an `index.ts` barrel that:
 *   1. Re-exports all types from each piece file
 *   2. Exports a `KnownPieces` interface mapping piece names → Client types
 *   3. Exports a `knownPieceNames` runtime const used by the SDK client
 *
 * Convention:
 *   - Each file must export exactly one `export interface <Name>Client`.
 *   - Filename `npm-foo.ts` → piece name `foo`.
 *   - Filename `foo.ts` → piece name `foo`.
 *   - If both `foo.ts` and `npm-foo.ts` exist, the native `foo.ts` wins.
 */
export async function generateGeneratedIndex(generatedDir: string): Promise<void> {
  const entries = await readdir(generatedDir);
  const tsFiles = entries.filter(f => f.endsWith('.ts') && f !== 'index.ts');

  interface PieceEntry {
    file: string;        // basename without .ts
    pieceName: string;
    clientName: string;
    isNpm: boolean;
  }

  const pieces: PieceEntry[] = [];

  for (const file of tsFiles) {
    const content = await readFile(join(generatedDir, file), 'utf-8');
    const match = content.match(/export interface (\w+Client)\s*\{/);
    if (!match) continue;

    const clientName = match[1];
    const base = file.replace('.ts', '');
    const isNpm = base.startsWith('npm-');
    const pieceName = isNpm ? base.slice(4) : base;

    pieces.push({ file: base, pieceName, clientName, isNpm });
  }

  // Resolve conflicts: native file wins over npm-prefixed file
  const pieceMap = new Map<string, PieceEntry>();
  for (const p of pieces) {
    const existing = pieceMap.get(p.pieceName);
    if (!existing || (!p.isNpm && existing.isNpm)) {
      pieceMap.set(p.pieceName, p);
    }
  }

  const known = [...pieceMap.values()].sort((a, b) => a.pieceName.localeCompare(b.pieceName));

  let out = AUTOGEN_HEADER + '\n';

  // Import client types so they're in scope for the KnownPieces interface
  for (const p of known) {
    out += `import type { ${p.clientName} } from './${p.file}.js';\n`;
  }
  out += '\n';

  // Re-export all types from each piece file
  for (const p of known) {
    out += `export * from './${p.file}.js';\n`;
  }
  out += '\n';

  // KnownPieces interface
  out += 'export interface KnownPieces {\n';
  for (const p of known) {
    out += `  '${p.pieceName}': ${p.clientName};\n`;
  }
  out += '}\n\n';

  // Runtime piece-name list for the SDK client constructor
  out += 'export const knownPieceNames: ReadonlyArray<keyof KnownPieces> = [\n';
  for (const p of known) {
    out += `  '${p.pieceName}',\n`;
  }
  out += '] as const;\n';

  await writeFile(join(generatedDir, 'index.ts'), out, 'utf-8');
  debug('typegen', `wrote generated/index.ts (${known.length} pieces)`);
}

// ---------------------------------------------------------------------------
// SDK public index — src/sdk/index.ts
// ---------------------------------------------------------------------------

/**
 * Write (or overwrite) `src/sdk/index.ts` — the public package entry point.
 *
 * This file is fully static apart from the autogen header; all the
 * piece-dynamic types are handled by `generated/index.ts`.  We write it
 * automatically so that the AUTOGEN_HEADER stays consistent and the file
 * is never edited by hand.
 *
 * @param sdkDir  - Absolute path to `src/sdk/`
 */
export async function generateSdkIndex(sdkDir: string): Promise<void> {
  const out =
    AUTOGEN_HEADER +
    '\n' +
    '// Core SDK — client, errors, and options\n' +
    "export { createClient, FreePiecesClient } from './client.js';\n" +
    "export { FreePiecesError } from './types.js';\n" +
    "export type { FreePiecesClientOptions, PieceSummary, ActionResult } from './types.js';\n" +
    '\n' +
    '// All piece types + KnownPieces (auto-generated per installed pieces)\n' +
    "export * from './generated/index.js';\n";

  await writeFile(join(sdkDir, 'index.ts'), out, 'utf-8');
  debug('typegen', 'wrote sdk/index.ts');
}
