import { execSync } from 'node:child_process';
import { writeFile, readFile } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { existsSync, mkdirSync } from 'node:fs';
import ora from 'ora';
import chalk from 'chalk';
import { getNpmPackageInfo } from '../util/npm-registry.js';

/**
 * Install an @activepieces/piece-* npm package and generate a freepieces
 * wrapper stub in src/pieces/npm-<name>.ts.
 */
export async function installCommand(packageName: string): Promise<void> {
  // Normalise package name
  const pkg = packageName.startsWith('@activepieces/piece-')
    ? packageName
    : `@activepieces/piece-${packageName}`;

  const cwd = process.cwd();

  if (!existsSync(join(cwd, 'package.json'))) {
    console.error(chalk.red('No package.json found. Run this command inside a freepieces project.'));
    process.exit(1);
  }

  // 1. Fetch metadata
  const spinner = ora(`Fetching ${chalk.cyan(pkg)} metadata…`).start();
  let meta: Awaited<ReturnType<typeof getNpmPackageInfo>>;
  try {
    meta = await getNpmPackageInfo(pkg);
    spinner.succeed(`Found ${pkg}@${meta.version}`);
  } catch (err) {
    spinner.fail(String(err));
    process.exit(1);
  }

  // 2. npm install
  const s2 = ora(`Installing ${pkg}…`).start();
  try {
    execSync(`npm install ${pkg}`, { cwd, stdio: 'pipe' });
    s2.succeed(`Installed ${pkg}`);
  } catch (err) {
    s2.fail(`npm install failed: ${String(err)}`);
    process.exit(1);
  }

  // 3. Generate wrapper stub
  const pieceName = pkg.replace('@activepieces/piece-', '');
  const symbolName = toPieceSymbol(pieceName) + 'Piece';
  const wrapperFile = join(cwd, 'src', 'pieces', `npm-${pieceName}.ts`);

  if (!existsSync(join(cwd, 'src', 'pieces'))) {
    mkdirSync(join(cwd, 'src', 'pieces'), { recursive: true });
  }

  const wrapper = generateWrapper(pkg, pieceName, symbolName, meta.description ?? '');

  const s3 = ora(`Generating wrapper src/pieces/npm-${pieceName}.ts…`).start();
  try {
    await writeFile(wrapperFile, wrapper, 'utf-8');
    s3.succeed(`Wrapper created: src/pieces/npm-${pieceName}.ts`);
  } catch (err) {
    s3.fail(String(err));
    process.exit(1);
  }

  // 4. Update worker.ts marker block if it exists
  const workerPath = join(cwd, 'src', 'worker.ts');
  if (existsSync(workerPath)) {
    await addPieceToWorker(workerPath, symbolName, `./pieces/npm-${pieceName}`);
  }

  console.log(
    `\n${chalk.green('✓')} ${chalk.bold(pkg)} installed.\n` +
      `  Edit ${chalk.cyan(`src/pieces/npm-${pieceName}.ts`)} to complete the integration.\n` +
      `  Run ${chalk.green('fp deploy')} when ready.\n`,
  );
}

// ─── Exported helpers (used by tui.ts) ────────────────────────────────────

/** Convert kebab-case piece name to camelCase symbol name. */
export function toPieceSymbol(name: string): string {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/** Generate a wrapper stub file for an npm @activepieces piece. */
export function generateWrapper(pkg: string, pieceName: string, symbolName: string, description: string): string {
  return `/**
 * Wrapper for ${pkg}
 * ${description}
 *
 * This file was auto-generated by \`fp install ${pkg}\`.
 * Complete the auth and actions sections to integrate the piece.
 *
 * For OAuth2 pieces, set the corresponding client ID/secret secrets:
 *   npx wrangler secret put ${pieceName.toUpperCase().replace(/-/g, '_')}_CLIENT_ID
 *   npx wrangler secret put ${pieceName.toUpperCase().replace(/-/g, '_')}_CLIENT_SECRET
 */

import { createPiece } from '../framework/piece.js';
import type { PieceActionContext } from '../framework/types.js';

export const ${symbolName} = createPiece({
  name: '${pieceName}',
  displayName: '${capitalise(pieceName)} (npm)',
  description: '${description.replace(/'/g, "\\'")}',
  version: '0.1.0',
  /**
   * Choose auth type: 'none' | 'apiKey' | 'oauth2'
   * For OAuth2 pieces provide authorizationUrl, tokenUrl, scopes.
   */
  auth: { type: 'none' },
  actions: [
    {
      name: 'run',
      displayName: 'Run',
      description: 'Execute the ${capitalise(pieceName)} action.',
      async run(_ctx: PieceActionContext): Promise<unknown> {
        // TODO: implement action using the ${pkg} package
        // import { piece } from '${pkg}';
        throw new Error('Action not yet implemented — edit src/pieces/npm-${pieceName}.ts');
      },
    },
  ],
});
`;
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

async function addPieceToWorker(workerPath: string, symbol: string, importPath: string): Promise<void> {
  const IMPORT_START = '// @fp:imports:start';
  const IMPORT_END = '// @fp:imports:end';
  const REGISTER_START = '// @fp:register:start';
  const REGISTER_END = '// @fp:register:end';

  let content = await readFile(workerPath, 'utf-8');
  if (!content.includes(IMPORT_START)) return; // no markers — skip

  // Add import if not already present
  if (!content.includes(importPath)) {
    const si = content.indexOf(IMPORT_END);
    content =
      content.slice(0, si) +
      `import { ${symbol} } from '${importPath}.js';\n` +
      content.slice(si);
  }

  // Add registerPiece call if not already present
  if (!content.includes(`registerPiece(${symbol})`)) {
    const ri = content.indexOf(REGISTER_END);
    content =
      content.slice(0, ri) +
      `registerPiece(${symbol});\n` +
      content.slice(ri);
  }

  await writeFile(workerPath, content, 'utf-8');
}
